services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        ports:
          - "5057:5057"
        volumes:
            - ./backend/:/app
        networks:
            - compose_network
    db:
        build:
           context: ./db
           dockerfile: Dockerfile
        ports:
          - "5432:5432"
        networks:
            - compose_network
        volumes:
            - db:/var/lib/postgresql/data
        restart: unless-stopped


    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
          - ./frontend:/app
          - /app/node_modules
        environment:
          - WATCHPACK_POLLING=true #enable polling
        ports:
          - "5173:5173"
        restart: unless-stopped

    tf:
        build:
            context: ./tf
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
        - "8501:8501"
        - "8500:8500"
        volumes:
            - tf:/models
        networks:
          - compose_network


    ml: 
        build: #satish was here
            context: ./ml
            dockerfile: Dockerfile
        networks:
            - compose_network
        volumes:
            - ./ml:/app #for hot reload
            - tf:/app/models
        restart: unless-stopped

    cache:
        build:
            context: ./cache
            dockerfile: Dockerfile
        ports:
          - 6379:6379
        networks:
          - compose_network
        hostname: redis
        volumes:
          - cache:/data
        command: redis-server
        restart: unless-stopped
        

volumes:
  db:
  cache:
  tf:

networks:
  compose_network:
    driver: bridge
