services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        ports:
          - "5057:5057"
        volumes:
            - ./backend/:/app
        networks:
            - compose_network
    db:
        build:
           context: ./db
           dockerfile: Dockerfile.dev
        ports:
          - "5432:5432"
        networks:
            - compose_network
        volumes:
            - db:/var/lib/postgresql/data
        restart: unless-stopped


    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
          - ./frontend:/app
          - /app/node_modules
        environment:
          - WATCHPACK_POLLING=true #enable polling
        ports:
          - "5173:5173"
        restart: unless-stopped

    tf:
        build:
            context: ./tf
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
        - "8501:8501"
        - "8500:8500"
        volumes:
            - tf:/models
        networks:
          - compose_network


    worker: 
        build: #satish was here
            context: ./worker
            dockerfile: Dockerfile
        networks:
            - compose_network
        volumes:
            - ./worker:/app #for hot reload
            - tf:/models
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 32g
              cpus: '4.0'
                #ulimits:
                #stack: 65536

    cache:
        build:
            context: ./cache
            dockerfile: Dockerfile
        ports:
          - 6379:6379
        networks:
          - compose_network
        hostname: redis
        volumes:
          - cache:/data
        command: redis-server
        restart: unless-stopped
        

volumes:
  db:
  cache:
  tf:

networks:
  compose_network:
    driver: bridge
