apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_ROOT_PASSWORD: ZGV2cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: dGVzdHJlZGlzMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: polygon-secret
type: Opaque
data:
  api-key: b2dhcXFrd1UxcENpX3g1Zmw5N3BHQXlXdGRoVkxKWW0=
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
data:
  GEMINI_FREE_KEYS: QUl6YVN5Q0FiOTJUWVBUVlRyVDVpazBBRjQ0VkRhNlRJT1c4bTdzLEFJemFTeUMxX21UYVRFZ05UMmc5UVlQRHE4MUg4dXQ2Rjk0Y015TSxBSXphU3lEQ29QY1JsdVBBYUZYYUI1U3QyLWQ4ejVqdjNuQUIwYkksQUl6YVN5QWFfS3BHLTVpQi13d0VCNWpZTnRLUUhCTWNTZXNDdC1ZLEFJemFTeUFjbVZUNTFpT1JZMW5GRDNSTHFZSVA3UTQtNGU1b1M3NA==
---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
type: Opaque
data:
  GOOGLE_CLIENT_ID: ODMxNjE1NzA2MDYxLXVvanMxa2psNGxoZTcwY3JtZjc3MXMyczJkZmxlanBvLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLVNibmVNeUV6RFZWYUhvTE1heHhhNE9MUWFReTc=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: blZtQWNMZW1tRWdqaDBXUlo5TjNMc2kyZFYvaGI2NHVtWCs1R0RWSjRqZz0=
