# IMPORTANT: THIS FILE IS FOR DEVELOPMENT PURPOSES ONLY
# Production deployment is handled via Kubernetes in the /prod directory
# The configurations below should NOT be used for actual production deployment

services:
    backend:
        build:
            context: ../services/backend
            dockerfile: Dockerfile.prod
        restart: unless-stopped
        networks:
            - compose_network

    db:
        build:
           context: ../services/db
           dockerfile: Dockerfile.prod
        networks:
            - compose_network
        volumes:
            - db:/var/lib/postgresql/data
            - ../backups:/backups
        restart: unless-stopped


    frontend:
        build:
            context: ../services/frontend
            dockerfile: Dockerfile.prod
        environment:
          - WATCHPACK_POLLING=true #enable polling
        restart: unless-stopped
        networks:
            - compose_network

    tf:
        build:
            context: ../services/tf
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - tf:/models
        networks:
          - compose_network


    worker: 
        build: #satish was here
            context: ../services/worker
            dockerfile: Dockerfile
        networks:
            - compose_network
        volumes:
          #- ./ml:/app #for hot reload
            - tf:/models
        restart: unless-stopped

    cache:
        build:
            context: ../services/cache
            dockerfile: Dockerfile
        networks:
          - compose_network
        hostname: redis
        volumes:
          - cache:/data
        command: redis-server
        restart: unless-stopped


    nginx:
        build:
            context: ../services/nginx
            dockerfile: Dockerfile
              #ports:
              #- "80:80"
        depends_on:
          - backend
          - frontend
        networks:
          - compose_network


    cloudflared:
      image: cloudflare/cloudflared:latest
      command: tunnel run --token eyJhIjoiYTAxOGU0Yzg4YmUwZWQ0NGRhN2VhNTY4YjMxMTZiM2MiLCJ0IjoiMjdjMzY2MGUtMmI4YS00YTE1LWIwMDAtOGVjZWYxMjFmYjdjIiwicyI6IllXUmhPVE5pT0dFdE5qUTBOUzAwWTJZM0xXSTVZV0l0TlRaaU9XVTRObVJoWkdFMiJ9
      restart: unless-stopped
      networks:
        - compose_network
        

volumes:
  db:
  cache:
  tf:

networks:
  compose_network:
    driver: bridge
