apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
spec:
  hard:
    pods: "1"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PodSelector
        values:
          - backend
