apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
  namespace: ${K8S_NAMESPACE}
spec:
  backoffLimit: 2 
  template:
    spec:
      containers:
        - name: db-migrate
          image: ${DOCKER_USERNAME}/db:${DOCKER_TAG}-migrations
          command:
            - sh
            - -c
            - |
              until pg_isready -h "$DB_HOST" -p 5432 -U "$DB_USER"; do
                echo "Waiting for Postgres..."
                sleep 2
              done
              migrate -path /migrations -database "postgres://$DB_USER:$DB_PASS@$DB_HOST:5432/$DB_NAME?sslmode=disable" up
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_NAME
              value: "postgres"
            - name: DB_HOST
              value: "db"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_ROOT_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  activeDeadlineSeconds: 300 
  ttlSecondsAfterFinished: 300
