apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: ${REDIS_PASSWORD_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_ROOT_PASSWORD: ${DB_PASSWORD_B64}
  db-password: ${DB_PASSWORD_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: polygon-secret
type: Opaque
data:
  api-key2-5: ${POLYGON_API_KEY_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
type: Opaque
data:
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_B64}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
type: Opaque
data:
  tunnel-token: ${CLOUDFLARE_TUNNEL_TOKEN_B64}
