services:
  backend:
    build:
      context: ../../services/backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5058:5058"
    volumes:
      - ../../services/backend/:/app
    networks:
      - compose_network
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=devpassword
      - DB_HOST=db
      - POSTGRES_DB=postgres
      - GEMINI_FREE_KEYS=${GEMINI_FREE_KEYS}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - X_API_KEY=${X_API_KEY}
      - TWITTER_API_IO_KEY=${TWITTER_API_IO_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      #- GITHUB_TOKEN=${GITHUB_TOKEN}
    platform: ${PLATFORM:-linux/amd64}
  db:
    build:
      context: ../../services/db
      dockerfile: Dockerfile.dev
    ports:
      - "5432:5432"
    networks:
      - compose_network
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=postgres
    platform: ${PLATFORM:-linux/amd64}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4.0'
  frontend:
    build:
      context: ../../services/frontend
      dockerfile: Dockerfile.dev
    platform: ${PLATFORM:-linux/amd64}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../services/frontend:/app
      - ../../services/frontend/node_modules:/app/node_modules
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true #enable polling
      - BACKEND_URL=http://backend:5058
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - compose_network

  cache:
    build:
      context: ../../services/cache
      dockerfile: Dockerfile
    platform: ${PLATFORM:-linux/amd64}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 6379:6379
    networks:
      - compose_network
    hostname: redis
    volumes:
      - cache:/data
    command: redis-server --maxclients 1000 --tcp-keepalive 60 --timeout 300 --appendonly yes --maxmemory 800mb --maxmemory-policy allkeys-lru --io-threads 4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'

  worker:
    build:
      context: ../../services/worker
      dockerfile: Dockerfile.dev
    platform: ${PLATFORM:-linux/amd64}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - compose_network
    restart: unless-stopped
    volumes:
      - ../../services/worker:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=devpassword
      - DB_HOST=db
      - POSTGRES_DB=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - HOT_RELOAD=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1g
          cpus: '1.0'

volumes:
  db:
  cache:
  tf:


networks:
  compose_network:
    driver: bridge
