apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # This will be replaced by the GitHub workflow with the actual secret
  redis-password: ${REDIS_PASSWORD_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # These will be replaced by the GitHub workflow with the actual secrets
  db_ROOT_PASSWORD: ${DB_PASSWORD_B64}
  db-password: ${DB_PASSWORD_B64}

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
type: Opaque
data:
  tunnel-token: ${CLOUDFLARE_TUNNEL_TOKEN_BASE64}
