apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_ROOT_PASSWORD: 
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: 
---
apiVersion: v1
kind: Secret
metadata:
  name: polygon-secret
type: Opaque
data:
  api-key: 
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
data:
  GEMINI_FREE_KEYS: 
---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
type: Opaque
data:
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: 
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
type: Opaque
data:
  CLOUDFLARE_TUNNEL_TOKEN: 
